from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO

def generate_pdf(data, mode="invoice", output_path=None):
    """
    Generate an invoice PDF from a data dictionary using ReportLab.

    Expected 'data' structure:
    {
        "business_name": "LAC Invoice Generator",
        "client_name": "Demo Client",
        "reference": "INV-001",
        "items": [
            {"description": "Website Design", "quantity": 1, "unit_price": 15000, "total": 15000},
            ...
        ]
    }
    """
    # Create a BytesIO buffer to save the PDF in memory
    buffer = BytesIO()

    # Set up the PDF canvas
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 18)
    c.drawString(100, height - 100, data.get("business_name", "Invoice"))
    c.setFont("Helvetica", 12)
    c.drawString(100, height - 130, f"Client: {data.get('client_name', 'Demo Client')}")
    c.drawString(100, height - 160, f"Reference No: {data.get('reference', 'INV-001')}")

    # Table Header
    c.setFont("Helvetica-Bold", 10)
    c.drawString(100, height - 200, "Description")
    c.drawString(300, height - 200, "Qty")
    c.drawString(400, height - 200, "Unit Price")
    c.drawString(500, height - 200, "Total")

    # Table Content
    y_position = height - 220
    subtotal = 0
    items = data.get("items", [])
    if not items:
        c.drawString(100, y_position, "No items available.")
    else:
        for item in items:
            description = str(item.get("description", "")).strip()
            qty = float(item.get("quantity", 1))
            unit_price = float(item.get("unit_price", 0))
            total = float(item.get("total", qty * unit_price))
            subtotal += total

            # Draw the table rows
            y_position -= 20
            c.drawString(100, y_position, description)
            c.drawString(300, y_position, str(qty))
            c.drawString(400, y_position, f"R{unit_price:,.2f}")
            c.drawString(500, y_position, f"R{total:,.2f}")

    # Calculate VAT and total due
    vat = subtotal * 0.15
    total_due = subtotal + vat

    # Draw totals
    y_position -= 40
    c.drawString(400, y_position, f"Subtotal: R{subtotal:,.2f}")
    y_position -= 20
    c.drawString(400, y_position, f"VAT (15%): R{vat:,.2f}")
    y_position -= 20
    c.drawString(400, y_position, f"Total Due: R{total_due:,.2f}")

    # Footer
    y_position -= 40
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(100, y_position, "Thank you for your business.")
    y_position -= 20
    c.drawString(100, y_position, "Generated by LAC Accounting Automations")

    # Save the PDF to the buffer
    c.save()

    # Get the PDF data from the buffer
    pdf = buffer.getvalue()

    # Save to a file if output_path is provided
    if output_path:
        with open(output_path, "wb") as f:
            f.write(pdf)
    else:
        return pdf
